services:
  - type: web
    name: laravel-app
    runtime: docker
    repo: https://github.com/leoneloliver/full-stack-challenge
    branch: main
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
