services:
  - type: web
    name: laravel-app
    env: php
    plan: free
    buildCommand: composer install && npm install && npm run build && touch database/database.sqlite && php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:GLr7Nb8V43Jbw3CDpKXhus/NWbvZ61Un1wQO/02LFsk=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          name: laravel-app
          type: web
          property: url
      - key: DB_CONNECTION
        value: sqlite
